### PR TITLE
Removed SafeArea from the screen to avoid ugly UI

### PR DESCRIPTION
**Pull request by awazgyawali**
## Before and After Images

<table>
  <tr>
    <td><strong>Before</strong></td>
    <td><strong>After</strong></td>
  </tr>
  <tr>
    <td>After Image</td>
    <td>Before Image</td>
  </tr>
</table>

### CODE REVIEW

**Comment by awazgyawali** [comment]
I hope this gets merged.

**Comment by Biplab-Dutta** [comment]
@awazgyawali Thanks for the PR.

**Comment by awazgyawali** [comment]
Can you also release this? @Biplab-Dutta

**Comment by Biplab-Dutta** [comment]
There will be some changes in the SDK. So, I was thinking of publishing all the changes together. I will do it by today.
@awazgyawali

**Comment by Biplab-Dutta** [comment]
The new SDK should be available by tomorrow if it passes through QA. @awazgyawali 
Until then, you are suggested to use the old version or a forked one.
If you wish to see the newer implementations, you can refer to https://github.com/khalti/checkout-sdk-flutter/tree/biplab-khalti/enhancement/return_url

**Pull request merged**
